import Head from 'next/head'
import Image from 'next/image'

import SearchBar from '../Components/SearchBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <SearchBar/>

      
    </div>
  )
}
